# Default configuration for WireSegHR (segmentation-only)
backbone: mit_b2
pretrained: true  # Uses HF SegFormer weights if available; else timm or tiny fallback

coarse:
  train_size: 512
  test_size: 1024

fine:
  patch_size: 768
  overlap: 128

conditioning:
  cond_from: coarse_logits_1x1
  cond_crop: patch  # per published method (method_yq)

minmax:
  enable: true
  kernel: 6  # fixed 6x6 luminance min/max

label:
  coarse_downsample: maxpool

inference:
  alpha: 0.01
  prob_threshold: 0.3 # was 0.5, not actually mentioned in the paper.
  stitch: avg_logits

optim:
  iters: 2000
  batch_size: 4
  lr: 6e-5
  weight_decay: 0.01
  schedule: poly
  power: 1.0
  precision: fp32  # one of: fp32, fp16, bf16

# training housekeeping
seed: 42
out_dir: runs/wireseghr
eval_interval: 100
ckpt_interval: 300
# resume: runs/wireseghr/ckpt_1500.pt  # optional

# dataset paths (placeholders)
data:
  train_images: dataset/train/images
  train_masks: dataset/train/gts
  val_images: dataset/val/images
  val_masks: dataset/val/gts
  test_images: dataset/test/images
  test_masks: dataset/test/gts
